const SECONDS = 10000; // how much is 1 second?

export const config = {
  seconds: SECONDS,
  timescale: 1,
  game: {
    version: "0.1.0",
    debug_mode: ["127.0.0.1", "localhost", "shooty3.surge.sh"].includes(window.location.hostname),
    invincibility_time: 1.5 * SECONDS,
    autosave_interval: 1 * SECONDS,
    level_1_xp: 1000,
    fall_damage: 100,
    coin_drop_mult: 1,
    coin_attractor_mult: 1,
  },
  physics: {
    wall_width: 8,
    player_speed: 8,
    player_jump: 0.02,
    player_gravity: 0.001,
    coyote_time: 0.111 * SECONDS,
    jump_reload_time: 2 * SECONDS,
    train_speed: 10,
    force_factor: 0.0005,
    recoil_factor: 10,
    velocity_shoot_boost: 0.3,
    drag_max_velocity: 15,
  },
  graphics: {
    fps: 60,
    resolution_mult: 1,
    particle_setting: 0,
    debug_display: false,
    fullscreen: false,
    shape_cull_padding: 50, // 16 should be ok, 50 is just to be safe
    linewidth_mult: 6,
    linewidth_max_mult: 20,
    shadowblur: 75,
    xp_hide_bar: false,
    xp_display_smoothness: 0.08,
    xp_display_time: 2 * SECONDS,
    collect_display_time: 3 * SECONDS,
    collect_display_fancy_slide: true,
    health_display_smoothness: 0.07,
    health_rotate_speed: 0.8,
    map_fade_time: 0.3 * SECONDS,
    map_move_speed: 50,
    blink_time: 0.15 * SECONDS,
    camera_smoothness: 0.18,
    camera_target_smoothness: 0.1,
    camera_mouse_look_factor: 0.075,
    pause_opacity: 0.25,
  },
};